export const ProductsData = [
    {
      id: 1,
      title: 'Churros Nutella',
      category: 'churros',
      price: 15.99,
      amount: 0,
      descricao: `Churros con topping de doce de leite `,
      img: 'https://cooknenjoy.com/wp-content/uploads/2021/09/Churros-Facil-01-1536x1154.jpg',
    },
    {
      id: 2,
      title: 'Churros Arequipe',
      category: 'churros',
      price: 13.99,
      amount: 0,
      descricao: `Churros con topping de doce de leite `,
      img: 'https://i0.wp.com/centralblogs.com.br/wp-content/uploads/2022/03/churros-com-doce-de-leite.jpg?resize=780%2C530&ssl=1',
    },
    {
      id: 3,
      title: 'Cocacola',
      category: 'drinks',
      price: 6.99,
      amount: 0,
      descricao: `Refrigerante con Sabor a Coca`,
      img: 'https://st.depositphotos.com/1007097/3992/i/450/depositphotos_39926881-stock-photo-coke-cola-033l-can.jpg',
    },
    {
      id: 4,
      title: 'Combo Mix',
      category: 'combos',
      price: 20.99,
      amount: 0,
      descricao: `Churros de nutella e cocacola`,
      img: "https://tofuu.getjusto.com/orioneat-prod-resized/Qnvam36oD2yGa88dv-1200-1200.webp",
    },
    {
      id: 5,
      title: 'Fanta Laranja',
      category: 'drinks',
      price: 22.99,
      amount: 0,
      descricao: `Refrigerante Sabor Laranja `,
      img: 'https://www.drogariaminasbrasil.com.br/media/product/dc1/refrigerante-fanta-laranja-lata-350ml-6eb.jpg',
    },
    {
      id: 6,
      title: 'Churritos Mixtos',
      category: 'combos',
      price: 18.99,
      amount: 0,
      descricao: `Churros de Nutela e Doce de Leite e Cocacola`,
      img: 'https://www.anamariabrogui.com.br/assets/uploads/receitas/fotos/usuario-3707-a6a076a8a0363226e5209c348ceeded6.jpg',
    },
    {
      id: 7,
      title: 'Suco Natural',
      category: 'drinks',
      price: 8.99,
      amount: 0,
      descricao: `Sabores: Maracuja, Goiaba, Abacaxi`,
      img: 'https://www.receiteria.com.br/wp-content/uploads/receitas-de-suco.jpg',
    },
    {
      id: 8,
      title: 'Churros Canela e Açucar',
      category: 'churros',
      price: 12.99,
      amount: 0,
      descricao: `Churros con Canela e Açucar `,
      img: 'https://i.ytimg.com/vi/IIXb0IiQrWs/maxresdefault.jpg',
    },
    {
      id: 9,
      title: 'Churro Frenesi',
      category: 'churros',
      price: 16.99,
      amount: 0,
      descricao: `Churros con topping de morango`,
      img: 'https://www.anamariabrogui.com.br/assets/uploads/receitas/fotos/usuario-3707-a6a076a8a0363226e5209c348ceeded6.jpg',
    },
  ];